# Generated by Django 2.2.18 on 2021-03-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Myuser',
        ),
    ]
