# Generated by Django 2.2.18 on 2021-03-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210328_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
