# Generated by Django 2.2.18 on 2021-03-28 04:06

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('price', models.EmailField(max_length=254)),
                ('published_time', partial_date.fields.PartialDateField()),
                ('publisher', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('cate_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.Category')),
            ],
        ),
    ]
