# Generated by Django 2.2.18 on 2021-03-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210328_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='cate_id',
        ),
        migrations.AlterField(
            model_name='book_cate',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', to_field='id'),
        ),
        migrations.AlterField(
            model_name='book_cate',
            name='cate_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.Category', to_field='id'),
        ),
    ]
