# Generated by Django 2.2.18 on 2021-03-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210328_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cate',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='book_cate',
            name='cate_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.Category'),
        ),
    ]
