# Generated by Django 2.2.18 on 2021-03-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210328_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Book List'},
        ),
        migrations.AlterModelOptions(
            name='book_cate',
            options={'verbose_name_plural': "Book's Category"},
        ),
    ]
