# Generated by Django 2.2.18 on 2021-03-28 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210328_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_cate',
            name='id',
        ),
        migrations.AlterField(
            model_name='book_cate',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book_cate',
            name='cate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
